the_things_list/urls.py
from django.conf.urls import url

from . import views

app_name = 'the_things_list'
urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='index'),
    url(r'^create/$', views.CreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.ThingView.as_view(), name='thing-details'),
    url(r'^edit/(?P<random_str>[0-9A-Za-z]+)/$', views.UpdateThing.as_view(),
        name='thing-update'),
    url(r'^edit/(?P<random_str>[0-9A-Za-z]+)/delete$', views.DeleteThing.as_view(), name='thing-delete'),
    url(r'^(?P<pk>[0-9]+)/contact/$', views.ContactView.as_view(), name='thing-contact')
]

thingslist/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('the_things_list.urls')),
]

the_things_list/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

"""
Database model of Things, more precisely announcements
"""


class Thing(models.Model):
    # Title of the announcement
    title = models.CharField(max_length=200)
    # Text of the announcement
    text = models.TextField()
    # Author, identified by the e-mail field
    author = models.EmailField()
    # last edit time, the announcements are sorted by this on the front page
    lastEdit = models.DateTimeField('Timestamp', default=timezone.now)
    # random token, used for editing announcements
    random_str = models.CharField(max_length=32, unique=True)

    def get_absolute_url(self):
        return reverse('the_things_list:thing-details',
                       kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

the_things_list/forms.py
from django import forms


class ContactForm(forms.Form):
    author = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

the_things_list/views.py
from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.utils.crypto import get_random_string
from django.views import generic

from .forms import ContactForm
from .models import Thing

"""
Generic view which lists all Things on the front page
"""


class HomeView(generic.ListView):
    template_name = 'the_things_list/index.html'
    context_object_name = 'all_things'

    def get_queryset(self):
        # Getting all Thing objects in the home page ordered by the last edit
        return Thing.objects.all().order_by('lastEdit')


"""
Generic detailed view of each Thing
"""


class ThingView(generic.DetailView):
    model = Thing
    template_name = 'the_things_list/view.html'


"""
Generic view for creating new Things
"""


class CreateView(generic.edit.CreateView):
    model = Thing
    fields = ['title', 'text', 'author']

    def form_valid(self, form):
        # random 32 character long string is created
        r_str = get_random_string(length=32)
        # get a site domain
        current_domain = Site.objects.get_current().domain
        # generate a full editing url
        full_url = current_domain + "/edit/" + r_str
        # save random token to the Thing object for future mapping
        form.instance.random_str = r_str
        # send an email to the user with editing url
        send_mail('link for editing', full_url, 'from@example.com', [form.instance.author], fail_silently=False)
        return super(CreateView, self).form_valid(form)


"""
Generic view for deleting Things and going back to the index
"""


class DeleteThing(generic.edit.DeleteView):
    success_url = reverse_lazy('the_things_list:index')

    # override get_object method such that the object is not matched by pk and therefore deleted
    def get_object(self, queryset=None):
        return Thing.objects.get(random_str=self.kwargs.get('random_str'))


"""
Generic view for editing Thing
"""


class UpdateThing(generic.edit.UpdateView):
    fields = ['title', 'text']
    template_name = 'the_things_list/updatething_form.html'

    # Override get_object() method such that we can use random token instead of pk in link
    def get_object(self, queryset=None):
        return Thing.objects.get(random_str=self.kwargs.get('random_str'))


"""
Generic View with for contacting the author of Thing.
Uses get() method to get the Thing object for which the user wants to contact the author.
Uses post() method to send an e-mail to the author of the Thing.
"""


class ContactView(generic.View):
    template_name = 'the_things_list/contact_form_template.html'
    form_class = ContactForm

    def get(self, request, pk):
        thing = Thing.objects.get(pk=pk)
        return render(request, self.template_name, {'thing': thing})

    def post(self, request, pk):
        form = self.form_class(request.POST)
        thing = Thing.objects.get(pk=pk)
        if form.is_valid():
            message = form.cleaned_data['message']
            author = form.cleaned_data['author']
            send_mail('Contact message', 'Message regarding your Thing: ' + thing.title + '\n ' + message, author,
                      [thing.author], fail_silently=False)

        return redirect('the_things_list:thing-details', pk=pk)

templates/the_things_list/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TheThingsList Home</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="{% static 'the_things_list/css/clean-blog.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'the_things_list/css/clean-blog.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'the_things_list/css/home-css.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'the_things_list/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>
    <script src="{% static 'the_things_list/vendor/jquery/jquery.min.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script src="{% static 'the_things_list/js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'the_things_list/js/clean-blog.min.js' %}"></script>

</head>
<body background="{% static 'the_things_list/img/home.jpg' %}">
<nav id="userNavBar" class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="{% url 'the_things_list:index' %}">TheThingsList</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'the_things_list:create' %}">Create a Thing</a></li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
<hr>
</html>

templates/the_things_list/contact_form_template.html
{% extends 'the_things_list/base.html' %}
{% block body %}
    <div id="homeDiv" class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">

                <div class="panel-body">
                    <div id="postDiv" class="container-fluid" style="margin-bottom:50px;">

                        <h4>Contact {{ thing.author }} about {{ thing.title }}</h4>

                    </div>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">

                            <label class="col-sm-2 col-md-2" for="author">
                                E-mail
                            </label>
                            <div class="col-sm-10 col-md-10">
                                            <input type="email" name="author">
                            </div>
                            <label class="col-sm-2 col-md-2" for="message">
                                Message
                            </label>

                            <div class="col-sm-10 col-md-10">

                                            <textarea rows="4" cols="50" id="message" maxlength="500"
                                                      name="message"
                                            ></textarea>
                            </div>


                            <div class="col-sm-offset-2 col-sm-10">

                                <button type="submit" class="btn btn-success">Submit</button>

                            </div>

                        </div>

                    </form>

                </div>

            </div>

        </div>
    </div>

{% endblock %}

templates/the_things_list/create.html
{% extends 'the_things_list/base.html' %}
{% block body %}
    <div id="homeDiv" class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">

                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'the_things_list/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">

                                <button type="submit" class="btn btn-success">Submit</button>

                            </div>

                        </div>

                    </form>

                </div>

            </div>

        </div>
    </div>

{% endblock %}

templates/the_things_list/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>

        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

templates/the_things_list/index.html
{% extends 'the_things_list/base.html' %}
{% load staticfiles %}


{% block body %}
    {% if all_things %}
        <div id="homeDiv" class="container-fluid" style="padding-bottom: 10px">
        <div class="col-sm-12">
            <h1 align="center">All Things</h1>
        </div>


        {% for thing in all_things %}
            <div class="col-sm-4 col-lg-2">
                <div class="thumbnail" >
                    <center><a href="{% url 'the_things_list:thing-details' thing.id%}">{{ thing.title }} </a></center>
                    <div class="caption" style="margin-top: 30px;">
                        <h4>by {{ thing.author }}</h4>
                        <p>Last edit on: {{ thing.lastEdit }}</p>

                    </div>
                </div>
            </div>
            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}

        {% endfor %}

    {% else %}
        <div id="homeDiv" class="container-fluid"><h3>No posts to show</h3></div>

    {% endif %}

</div>

{% endblock %}

templates/the_things_list/thing_form.html
{% extends 'the_things_list/base.html' %}
{% block body %}
    <div id="homeDiv" class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">

                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'the_things_list/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">

                                <button type="submit" class="btn btn-success">Submit</button>

                            </div>

                        </div>

                    </form>

                </div>

            </div>

        </div>
    </div>

{% endblock %}

templates/the_things_list/updatething_form.html
{% extends 'the_things_list/base.html' %}
{% block body %}
    <div id="homeDiv" class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">

                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'the_things_list/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">

                                <button type="submit" class="btn btn-success">Submit</button>

                            </div>
                        </div>
                    </form>
                </div>

            </div>

            <div class ="col-sm-12 col-md-1">
                <div class="panel-body">
                    <form action="{% url 'the_things_list:thing-delete' thing.random_str %}" method="post" style="display: inline;">
                                {% csrf_token %}

                        <button type="submit" class="btn btn-default btn-sm">

                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            Delete Thing

                        </button>

                    </form>

                </div>
            </div>

        </div>

    </div>

{% endblock %}

templates/the_things_list/view.html
{% extends 'the_things_list/base.html' %}
{% load staticfiles %}

{% block body %}
    <link href="{% static 'the_things_list/css/post-css.css' %}" rel="stylesheet">
    <div id="homeDiv" class="container-fluid">
        <div id="postDiv" class="container-fluid" style="margin-bottom:150px;">

            <h1>{{ thing.title }}</h1>
            <h3 class="lead">{{ thing.text }}</h3>
            <h4>by {{ thing.author }}</h4>

            <form action="{% url 'the_things_list:thing-contact' thing.pk %}">
                <button type="submit" href="{% url 'the_things_list:thing-contact' thing.pk %}"
                        class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
                </button>
            </form>

        </div>
    </div>
{% endblock %}